### ISSUE TITLE
Exception running C++ and Java wordcount example

### ISSUE THREAD

**Issue by comlor** [csula/cs-tools#5]
![screen shot 2016-03-08 at 11 57 11 pm](https://cloud.githubusercontent.com/assets/14832244/13628739/840c6040-e589-11e5-8dcd-f04717412786.png)

**Comment by john-csula** [comment]
Ok, the problem seems to be with the datanode not being setup correctly.  So I tracked the problem by simply typing `jps` and you should see something like this:

```
13627 Jps
13277 SecondaryNameNode
13021 NameNode
13144 DataNode
13499 TaskTracker
13364 JobTracker
```

Obviously the task id (integer) will vary.   However, you should see six processes running.  I noticed that `DataNode` was not running.  So by simply looking at the the log file:

```
cat /opt/hadoop-1.2.1/logs/hadoop-vagrant-datanode-node0.log  | less
```

I see that there is file system corruption.  So what's the fix?

```
stop-all.sh
rm -rf /app/hadoop/tmp/*
hadoop namenode -format
start-all.sh
``` 

Seems to do the trick.

**Comment by john-csula** [comment]
also be sure to get the latest `/etc/hosts` to look at this:

```
192.168.33.100  node0
192.168.33.101  node1
192.168.33.102  node2
192.168.33.103  node3
192.168.33.104  node4
```

One way is to re-clone https://github.com/csula/cs-tools and provision from scratch.

**Comment by john-csula** [comment]
This is resolved.
